### ISSUE TITLE
videojs(...).qualityPickerPlugin is not a function

### ISSUE THREAD

**Issue by Awais-cb** [streamroot/videojs-quality-picker#17]
every time i try to play the example its gives this error in console

> Uncaught TypeError: videojs(...).qualityPickerPlugin is not a function

any fix to this?
help would be really appreciated

**Comment by Awais-cb** [comment]
Uncaught TypeError: videojs(...).qualityPickerPlugin is not a function
quality picker not working even in demo

**Comment by ruslandinov** [comment]
Hello and thank you for your feedback! I'll check this and reply to you soon.

**Comment by Awais-cb** [comment]
well thank you for your response i figured it out actually
import and export functions were not working at that time as i was using simple JavaScript not node.js
but then i combine all the quality picker js code in one file and included into my project and it started working thanks for this awesome plugin :)
