### ISSUE TITLE
how to use this plugin for latest version of videojs please help i want to integrate this plugin with v 6.0.0 videojs

### ISSUE THREAD

**Issue by NAVNEETSINGH1** [streamroot/videojs-quality-picker#20]

**Comment by SolmazKh** [comment]
I have the same Problem.

**Comment by ruslandinov** [comment]
Thanks to @jienco this should be fix now, could you please try on latest master?

**Comment by SolmazKh** [comment]
oh, good. Would you please add a demo?

**Comment by ruslandinov** [comment]
We have an example page here https://github.com/streamroot/videojs-quality-picker/blob/master/example/index.html.

**Comment by jienco** [comment]
@SolmazKh I also did an example here https://embed.plnkr.co/97AbtBGwmreNRnIvmqV1/, using VideoJS 6.5.0 from cdnjs and including my compiled file of https://github.com/streamroot/videojs5-hlsjs-source-handler (which includes videojs-quality-picker internally, see https://github.com/streamroot/videojs5-hlsjs-source-handler/blob/master/lib/videojs5-hlsjs-source-handler.js#L1).

**Comment by SolmazKh** [comment]
@jienco  Thaknks
