### ISSUE TITLE
Plugin not compatible with VideoJS6

### ISSUE THREAD

**Issue by sdahdaah** [streamroot/videojs-quality-picker#23]
Hello,

This plugin is not compatible with VideoJS6 it uses tech_ of videojs5 that is not available with version 6.

Can you please upgrade it to work with V6.

**Comment by tri170391** [comment]
This issue should be resolved by https://github.com/streamroot/videojs-quality-picker/pull/24

**Comment by nitsuj102284** [comment]
@tri170391, Is there anything that that one needs to do in order for this to work in an instance of VideoJS 6? In v5, I simply included the HLSJS plugin from CDN, and called `player.qualityPickerPlugin()` and it worked. In v6, I receive the message: player.qualityPickerPlugin is not a function.

**Comment by tri170391** [comment]
We no longer include the plugin in the Hls.js plugin anymore, you can still build this repo to get the script and used it as described in `example/index.html`

**Comment by nitsuj102284** [comment]
Thanks! Will this work on VideoJS 7 too? Not using 7 yet, because of other issues, just wondering if Quality Picker is ready for it yet.

**Comment by tri170391** [comment]
It should, I did do a quick check on both the Hls.js plugin and this :wink:

**Comment by tri170391** [comment]
I pushed a PR and it will be merge after I have the team's approval. For now you can get the built version here https://github.com/streamroot/videojs-quality-picker/tree/update-tooling/dist

**Comment by nitsuj102284** [comment]
Thank you! Works great! I should be able to get the button with `player.getChild('PickerButton')`? I would like to move it to a menu that I registered to the player.

**Comment by tri170391** [comment]
I am not very familiar with the UI side of `videojs` (I am more specialize in the media side of it) but you can give it a shot and report a new issue for it I guess 😉

**Comment by nitsuj102284** [comment]
I guess that what I was asking was, what is the actual name of the component? If not 'PickerButton', what? I pulled the 'PickerButton' name from glancing at the minified code. It is undefined.

**Comment by tri170391** [comment]
Have you tried `videoPickerButton`?

**Comment by nitsuj102284** [comment]
☺️

**Comment by nitsuj102284** [comment]
I appreciate your help on this!
Is there any method to get the current playback quality, and any event for playback change/changing?

**Comment by tri170391** [comment]
It's not related to this plugin but you can use the hook mechanism we provided in the Hls.js videojs plugin to gain access to the underlying Hls.js instance. You can register to its event for your use case. I'm closing this since VJS6 is now working with the plugin.
