### ISSUE TITLE
Working Example 

### ISSUE THREAD

**Issue by sobytes** [streamroot/videojs-quality-picker#4]
Hi 

I was just wondering if there is a working example to reference for hls?

Thanks

When i try and run grunt build i get

```
grunt build̀
Warning: Task "build̀" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by sobytes** [comment]
There seems to be a weird hyphen in the build when i copied and pasted i typed it out normally and it worked fine.

**Comment by vegamedia** [comment]
Do you have working example online?

**Comment by rishigohil** [comment]
Do we have a working example for this?

**Comment by ruslandinov** [comment]
Hey guys, sorry about delayed answer. We released major tooling update for this plugin and introducing and example. Clone the repo, install the dependencies and run `npm run dev` -- it starts Webpack dev server with working example.
